package dkand12.Helpers;

public enum STATE {
	
	NO_SLOTS_AVAILABLE, 
	SLOT_PROVIDED,
	AWATING_CLIENT_HELLO,
	SUCCESS_EXIT,
	FORCED_SHUTDOWN,
	ERROR_EXIT,
	CLIENT_HELLO_RESPONDED,
	CLIENT_CHALLENGE_RESPONDED,
	Connection_Slot_Received,
	Cipher_Spec_Agreed,
	ClientChallange_Sent,
	ServerChallange_Responded,
	SENDING_PUBLICKEY_PART,
	WATING_COUNTER_KEYPART,
	SENDING_FINAL,
	PUBLISH_DH_SPEC,
	AWATING_PUBLICPART_RESPONSE,
	WATING_VERIFICATION_RESULT,
	AWATING_DH_PARAMETERS,
	AWATING_CLIENT_SIGNED,
	AWAIT_CLIENT_PUBLICPART
}
